# Generated by Django 4.1 on 2024-09-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idclientes', models.AutoField(db_column='idClientes', primary_key=True, serialize=False)),
                ('numerodocumento', models.CharField(db_column='numeroDocumento', max_length=45)),
                ('tipodocumento', models.CharField(db_column='tipoDocumento', max_length=2)),
                ('nombre1', models.CharField(max_length=45)),
                ('nombre2', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=300)),
                ('correo1', models.CharField(max_length=150)),
                ('correo2', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono1', models.CharField(max_length=13)),
                ('telefono2', models.CharField(blank=True, max_length=13, null=True)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('genero', models.CharField(max_length=9)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetalleventa', models.AutoField(db_column='idDetalleVenta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valorunitario', models.DecimalField(db_column='valorUnitario', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idinsumos', models.AutoField(db_column='idInsumos', primary_key=True, serialize=False)),
                ('nombreinsumo', models.CharField(db_column='nombreInsumo', max_length=150)),
                ('color', models.CharField(max_length=45)),
                ('unidaddemedida', models.CharField(db_column='unidadDeMedida', max_length=11)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecharegistro', models.DateTimeField(db_column='fechaRegistro')),
                ('imageninsumo', models.TextField(db_column='imagenInsumo')),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Metododepago',
            fields=[
                ('idmetododepago', models.AutoField(db_column='idMetodoDePago', primary_key=True, serialize=False)),
                ('metododepago', models.CharField(db_column='metodoDePago', max_length=15)),
            ],
            options={
                'db_table': 'metododepago',
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('idprivilegio', models.AutoField(db_column='idPrivilegio', primary_key=True, serialize=False)),
                ('nombreprivilegio', models.CharField(db_column='nombrePrivilegio', max_length=50)),
            ],
            options={
                'db_table': 'privilegio',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('tipoproveedor', models.CharField(db_column='tipoProveedor', max_length=8)),
                ('categoriaproveedor', models.CharField(db_column='categoriaProveedor', max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('sitioweb', models.CharField(blank=True, db_column='sitioWeb', max_length=500, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('nombre1', models.CharField(max_length=45)),
                ('nombre2', models.CharField(blank=True, max_length=45, null=True)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(blank=True, max_length=45, null=True)),
                ('nombreempresa', models.CharField(db_column='nombreEmpresa', max_length=100)),
                ('telefono1', models.CharField(max_length=13)),
                ('telefono2', models.CharField(blank=True, max_length=13, null=True)),
                ('correo1', models.CharField(max_length=150)),
                ('correo2', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='nombreRol', max_length=100)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventas', models.AutoField(db_column='idVentas', primary_key=True, serialize=False)),
                ('valortotal', models.DecimalField(db_column='valorTotal', decimal_places=0, max_digits=10)),
                ('fechaventa', models.DateTimeField(db_column='fechaVenta')),
                ('modalidadventa', models.CharField(db_column='modalidadVenta', max_length=10)),
                ('cliente_idclientes', models.ForeignKey(db_column='cliente_idClientes', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.cliente')),
                ('metododepago_idmetododepago', models.ForeignKey(db_column='metodoDePago_idMetodoDePago', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.metododepago')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusurios', models.AutoField(db_column='idUsurios', primary_key=True, serialize=False)),
                ('numerodocumento', models.CharField(db_column='numeroDocumento', max_length=20)),
                ('tipodedocumento', models.CharField(db_column='tipodeDocumento', max_length=2)),
                ('primernombre', models.CharField(db_column='primerNombre', max_length=45)),
                ('segundonombre', models.CharField(blank=True, db_column='segundoNombre', max_length=45, null=True)),
                ('primeraprellido', models.CharField(db_column='primerAprellido', max_length=45)),
                ('segundoaprellido', models.CharField(blank=True, db_column='segundoAprellido', max_length=45, null=True)),
                ('correo1', models.CharField(max_length=100)),
                ('correo2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=45)),
                ('rol_idrol', models.ForeignKey(db_column='rol_idRol', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.rol')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='nombreCategoria', max_length=100)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=100)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('calidad', models.CharField(max_length=7)),
                ('dimension', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=45)),
                ('observaciones', models.TextField()),
                ('imagenproducto', models.TextField(db_column='imagenProducto')),
                ('genero', models.CharField(max_length=9)),
                ('usuario_idusurios', models.ForeignKey(db_column='usuario_idUsurios', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.usuario')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Privilegiousuario',
            fields=[
                ('idprivilegiosusuarios', models.AutoField(db_column='idPrivilegiosUsuarios', primary_key=True, serialize=False)),
                ('fechaasignacion', models.DateTimeField(db_column='fechaAsignacion')),
                ('privilegio_idprivilegio', models.ForeignKey(db_column='privilegio_idPrivilegio', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.privilegio')),
                ('usuario_idusurios', models.ForeignKey(db_column='usuario_idUsurios', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.usuario')),
            ],
            options={
                'db_table': 'privilegiousuario',
            },
        ),
        migrations.CreateModel(
            name='Privilegiocliente',
            fields=[
                ('idprilegiocliente', models.AutoField(db_column='idprilegioCliente', primary_key=True, serialize=False)),
                ('fechaasignacion', models.DateTimeField(db_column='fechaAsignacion')),
                ('cliente_idclientes', models.ForeignKey(db_column='cliente_idClientes', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.cliente')),
                ('privilegio_idprivilegio', models.ForeignKey(db_column='privilegio_idPrivilegio', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.privilegio')),
            ],
            options={
                'db_table': 'privilegiocliente',
            },
        ),
        migrations.CreateModel(
            name='Ordendeproduccion',
            fields=[
                ('idordendeproduccion', models.AutoField(db_column='idOrdenDeProduccion', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=11)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('fechafinalizacion', models.DateTimeField(db_column='fechaFinalizacion')),
                ('detalleventa_iddetalleventa', models.ForeignKey(db_column='detalleVenta_idDetalleVenta', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.detalleventa')),
                ('usuario_idusurios', models.ForeignKey(db_column='usuario_idUsurios', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.usuario')),
            ],
            options={
                'db_table': 'ordendeproduccion',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_idproducto',
            field=models.ForeignKey(db_column='producto_idProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta_idventas',
            field=models.ForeignKey(db_column='venta_idVentas', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.venta'),
        ),
        migrations.CreateModel(
            name='Controlgastoinsumo',
            fields=[
                ('idcontrolgastoinsumo', models.AutoField(db_column='idControlGastoInsumo', primary_key=True, serialize=False)),
                ('fechauso', models.DateTimeField(db_column='fechaUso')),
                ('unidaddemedida', models.CharField(db_column='unidadDeMedida', max_length=11)),
                ('cantidad', models.IntegerField()),
                ('comentarios', models.TextField()),
                ('insumo_idinsumos', models.ForeignKey(db_column='insumo_idInsumos', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.insumo')),
                ('ordendeproduccion_idordendeproduccion', models.ForeignKey(db_column='ordenDeProduccion_idOrdenDeProduccion', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.ordendeproduccion')),
            ],
            options={
                'db_table': 'controlgastoinsumo',
            },
        ),
        migrations.CreateModel(
            name='Compraproducto',
            fields=[
                ('idcomprasproductos', models.AutoField(db_column='idComprasproductos', primary_key=True, serialize=False)),
                ('preciounitario', models.DecimalField(db_column='precioUnitario', decimal_places=0, max_digits=10)),
                ('preciototal', models.DecimalField(db_column='precioTotal', decimal_places=0, max_digits=10)),
                ('fechacompra', models.DateTimeField(db_column='fechaCompra')),
                ('cantidad', models.IntegerField()),
                ('producto_idproducto', models.ForeignKey(db_column='producto_idProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.producto')),
                ('proveedor_idproveedor', models.ForeignKey(db_column='proveedor_idProveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.proveedor')),
            ],
            options={
                'db_table': 'compraproducto',
            },
        ),
        migrations.CreateModel(
            name='Comprainsumo',
            fields=[
                ('idcomprasinsumos', models.AutoField(db_column='idComprasInsumos', primary_key=True, serialize=False)),
                ('preciounitario', models.DecimalField(db_column='precioUnitario', decimal_places=0, max_digits=10)),
                ('preciototal', models.DecimalField(db_column='precioTotal', decimal_places=0, max_digits=10)),
                ('fechacompra', models.DateTimeField(db_column='fechaCompra')),
                ('cantidad', models.IntegerField()),
                ('insumo_idinsumos', models.ForeignKey(db_column='insumo_idInsumos', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.insumo')),
                ('proveedor_idproveedor', models.ForeignKey(db_column='proveedor_idProveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='modulos.proveedor')),
            ],
            options={
                'db_table': 'comprainsumo',
            },
        ),
    ]
