# Generated by Django 4.1 on 2024-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='imageninsumo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='iimageninsumo',
            field=models.ImageField(blank=True, db_column='imagenInsumo', null=True, upload_to='imagenes_insumos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenproducto',
            field=models.ImageField(blank=True, db_column='imagenProducto', null=True, upload_to='imagenes_productos/'),
        ),
    ]
