# Generated by Django 4.1 on 2024-09-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_remove_insumo_imageninsumo_insumo_iimageninsumo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='iimageninsumo',
            new_name='imageninsumo',
        ),
    ]
