# Generated by Django 4.1 on 2024-09-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
