# Generated by Django 4.1 on 2024-09-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0010_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
