# Generated by Django 4.1 on 2024-09-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_insumo_codigo_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='valorunitario',
        ),
    ]
