# Generated by Django 4.1 on 2024-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0013_detalleventa_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numeroventa',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
