# Generated by Django 4.1 on 2024-09-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0017_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
